- name: Variables in Ansible
  hosts: web
  vars:
    COURSE: "DevOps"
    TRAINER: "Siva"
    DURATION: "120 Days"
  tasks:
  - name: Printing the variables
    ansible.builtin.debug:
      msg: "I m learning {{COURSE}} for {{DURATION}} under {{TRAINER}} training"