- name: Play book for passing vars from command prompt
  hosts: web
  vars_prompt:
    - name: Course
      prompt: "Enter the course"
      private: false
    
    - name: Duration
      prompt: "Enter the duartion"
      private: false

    - name: Trainer
      prompt: "Enter the trainer name"
      private: false
  tasks:
  - name: Task for printing the vars from prompt
    ansible.builtin.debug:
      msg: "I m learning {{Course}} for {{Duration}} under {{Tainer}} training"
