- name: Playbook for creating a user if not presents
  hosts: web
  become: yes
  tasks:
  - name: Task for getting expense user details
    ansible.builtin.command: id expense
    register: User # nothing but we are keeping the output of the previuos command in a variable User
    ignore_errors: true

  - name: Task for printing the output
    ansible.builtin.debug:
      msg: "user details as follows: {{User}}"