- name: Multi Play --01 
  hosts: web
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: "Hii This is from paly 01"

- name: Multi Play --02
  hosts: web
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: "Hii This is from paly 02"